// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Mpir.NET")]
[assembly: AssemblyProductAttribute("Mpir.NET")]
[assembly: AssemblyCopyrightAttribute("wezeku.com")]
[assembly: AssemblyDescriptionAttribute("MPIR library wrapper for .NET.")]
[assembly: AssemblyVersionAttribute("0.3.0")]
[assembly: AssemblyFileVersionAttribute("0.3.0")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.3.0";
    }
}
